baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Fission | Open source Kubernetes-native Serverless Framework'
theme = 'fission'

[params]
  installurl = ''
  learnmoreurl = ''

  [params.social]
    twitter = 'fissionio'
	slackurl = '/'
	github = 'geekboysupreme'

  [[params.whatsnew]]
    badge = 'FISSION DZONE REFCARD'
	heading = 'New! Download the Fission.io Refcard'
	body = 'Get started with Serverless on Kubernetes in 5 minutes! Learn how to set up Fission, its key concepts, how to create and invoke a function, monitor its performance, and more.'
	[params.whatsnew.button]
	  text = 'Download Now!'
	  url = ''
	  hero_class = 'mid'

  [[params.whatsnew]]
    badge = 'BLOG'
	heading = 'Monitor Fission serverless functions with OpenTracing'
	body = 'This post walks you through setting up OpenTracking, with a Jaeger backend, for tracing each request across multiple functions and invocations.'
	[params.whatsnew.button]
	  text = 'Read More!'
	  url = ''
	  hero_class = 'mid-2'

  [[params.whatsnew]]
    badge = 'PODCAST'
	heading = 'Talking Serverless on Kubernetes with Software Engineering Dail'
	body = 'Soam Vasani – the creator of Fission – sat down with Jeffrey Meyerson from Software Engineering Daily podcast to talk all-things serverless and Kubernetes.'
	[params.whatsnew.button]
	  text = 'Listen Now!'
	  url = ''
	  hero_class = 'mid-2'



[menu]
  [[menu.main]]
    name = "Overview"
    url = "/features.html"
	weight = 1
  [[menu.main]]
    name = "Docs"
    url = "/features.html"
	weight = 2
  [[menu.main]]
    name = "Community"
    url = "/features.html"
	weight = 3
  [[menu.main]]
    name = "Blog"
    url = "/features.html"
	weight = 4
  [[menu.main]]
    name = "Install"
    url = "/features.html"
	weight = 5
  [[menu.main]]
    name = "GitHub"
    url = "/features.html"
	weight = 6
