baseURL = 'https://fission.io/'
languageCode = 'en-us'
title = 'Fission | Open source Kubernetes-native Serverless Framework'
theme = 'fission'

[params]
  installurl = 'https://docs.fission.io/docs/installation/'
  learnmoreurl = 'https://docs.fission.io/docs/installation/'

  [params.social]
    twitter = 'fissionio'
	  slackurl = "https://join.slack.com/t/fissionio/shared_invite/enQtOTI3NjgyMjE5NzE3LTllODJiODBmYTBiYWUwMWQxZWRhNDhiZDMyN2EyNjAzMTFiYjE2Nzc1NzE0MTU4ZTg2MzVjMDQ1NWY3MGJhZmE"
	  github = 'fission'

  [[params.whatsnew]]
    badge = 'FISSION DZONE REFCARD'
	  heading = 'New! Download the Fission.io Refcard'
	  body = 'Get started with Serverless on Kubernetes in 5 minutes! Learn how to set up Fission, its key concepts, how to create and invoke a function, monitor its performance, and more.'
	[params.whatsnew.button]
	  text = 'Download Now!'
	  url = 'https://platform9.com/wp-content/uploads/2019/03/dzone-refcard-fissionio.pdf'
	  hero_class = 'mid'

  [[params.whatsnew]]
    badge = 'BLOG'
	  heading = 'Fission WebSocket Sample'
	  body = 'In this post we will look into how we can develop a simple a web socket based chat application using Fission functions.'
	[params.whatsnew.button]
	  text = 'Read More!'
	  url = 'https://blog.fission.io/posts/websocket-sample/'
	  hero_class = 'mid-2'

  [[params.whatsnew]]
    badge = 'PODCAST'
	heading = 'Talking Serverless on Kubernetes with Software Engineering Dail'
	body = 'Soam Vasani – the creator of Fission – sat down with Jeffrey Meyerson from Software Engineering Daily podcast to talk all-things serverless and Kubernetes.'
	[params.whatsnew.button]
	  text = 'Listen Now!'
	  url = 'https://platform9.com/blog/talking-serverless-on-kubernetes-with-software-engineering-daily'
	  hero_class = 'mid-2'

[menu]
  # [[menu.main]]
  #   name = "Overview"
  #   url = "/features.html"
	#   weight = 1
  [[menu.main]]
    name = "Docs"
    url = "https://docs.fission.io/docs/"
	  weight = 2
  # [[menu.main]]
  #   name = "Community"
  #   url = "/features.html"
	#   weight = 3
  [[menu.main]]
    name = "Blog"
    url = "https://blog.fission.io/"
	  weight = 3
  # [[menu.main]]
  #   name = "Install"
  #   url = "/features.html"
	#   weight = 5
  [[menu.main]]
    name = "Environments"
    url = "https://environments.fission.io/"
	  weight = 5
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/fission"
	  weight = 6
